import React, { useState, useEffect, useRef, useCallback } from 'react';
import { ArrayBar, BarStatus, SortingStep, AlgorithmDefinition, TreeNode, GraphNode, GraphEdge } from './types';
import { ALGORITHMS } from './algorithms';
import { DEFAULT_ARRAY_SIZE, DEFAULT_TREE_SIZE, ANIMATION_SPEED_MS } from './constants';
import Visualizer from './components/Visualizer';
import TreeVisualizer from './components/TreeVisualizer';
import GraphVisualizer from './components/GraphVisualizer';
import Controls from './components/Controls';
import AITutor from './components/AITutor';
import CodeViewer from './components/CodeViewer';
import { Info, Terminal, Github } from 'lucide-react';

const App: React.FC = () => {
  // State
  const [selectedAlgo, setSelectedAlgo] = useState<AlgorithmDefinition>(ALGORITHMS[0]);
  const [arraySize, setArraySize] = useState<number>(DEFAULT_ARRAY_SIZE);
  
  // Data States
  const [array, setArray] = useState<ArrayBar[]>([]);
  const [treeRoot, setTreeRoot] = useState<TreeNode | null>(null);
  const [graphState, setGraphState] = useState<{nodes: GraphNode[], edges: GraphEdge[]}>({ nodes: [], edges: [] });
  
  const [isPlaying, setIsPlaying] = useState(false);
  const [isSorted, setIsSorted] = useState(false);
  const [speed, setSpeed] = useState<number>(ANIMATION_SPEED_MS);
  const [currentStepDescription, setCurrentStepDescription] = useState<string>("Ready to start");
  const [activeLine, setActiveLine] = useState<number | undefined>(undefined);
  
  // Refs for loop control
  const generatorRef = useRef<Generator<SortingStep> | null>(null);
  const timeoutRef = useRef<number | null>(null);
  
  // Refs to access latest state inside callbacks without dependencies
  const arrayRef = useRef<ArrayBar[]>(array);
  const speedRef = useRef<number>(speed);

  useEffect(() => {
    arrayRef.current = array;
  }, [array]);

  useEffect(() => {
    speedRef.current = speed;
  }, [speed]);

  // Initialize Data
  const generateData = useCallback((size: number) => {
    // 1. Array Data (for Sorting)
    const uniqueValues = new Set<number>();
    while(uniqueValues.size < size) {
        uniqueValues.add(Math.floor(Math.random() * 85) + 5);
    }
    const values = Array.from(uniqueValues);
    const newArray: ArrayBar[] = values.map((val, i) => ({
      value: val,
      status: BarStatus.DEFAULT,
      id: `bar-${i}-${Date.now()}`
    }));
    setArray(newArray);
    arrayRef.current = newArray;
    
    // 2. Tree Data
    setTreeRoot(null);

    // 3. Graph Data
    setGraphState({ nodes: [], edges: [] }); // Graph is generated by the algo generator usually
    
    setIsSorted(false);
    generatorRef.current = null;
    setCurrentStepDescription("Ready to start");
    setActiveLine(undefined);
  }, []);

  // When selection changes or size changes
  useEffect(() => {
    setIsPlaying(false);
    if (timeoutRef.current) clearTimeout(timeoutRef.current);
    
    // Intelligent default size switching
    let targetSize = arraySize;
    if (selectedAlgo.type === 'tree' && arraySize > 15) {
        targetSize = DEFAULT_TREE_SIZE;
        setArraySize(targetSize);
    }
    // Graph default size
    if (selectedAlgo.type === 'graph' && arraySize > 8) {
        targetSize = 6;
        setArraySize(targetSize);
    }
    
    generateData(targetSize);
  }, [arraySize, selectedAlgo, generateData]);

  // Animation Step
  // We remove 'array' from dependencies to prevent function recreation on every step
  // which causes the useEffect below to fire and bypass the timeout
  const step = useCallback(() => {
    if (!generatorRef.current) {
      // Use the ref for initialization to avoid dependency
      generatorRef.current = selectedAlgo.generateSteps(arrayRef.current);
    }

    if (generatorRef.current) {
      const { value, done } = generatorRef.current.next();
      
      if (done) {
        setIsPlaying(false);
        setIsSorted(true);
        generatorRef.current = null;
        setCurrentStepDescription("Completed!");
        setActiveLine(undefined);
        return;
      }
      
      if (value) {
        // Handle updates based on algorithm type
        if (value.array) setArray(value.array);
        
        if (selectedAlgo.type === 'tree' && value.treeRoot !== undefined) {
             setTreeRoot(value.treeRoot);
        }
        if (selectedAlgo.type === 'graph' && value.graph) {
             setGraphState(value.graph);
        }

        if (value.description) {
            setCurrentStepDescription(value.description);
        }
        if (value.codeLine !== undefined) {
            setActiveLine(value.codeLine);
        }
        // Schedule next step using the ref speed
        timeoutRef.current = window.setTimeout(step, speedRef.current);
      }
    }
  }, [selectedAlgo]); // Only recreate if algo changes

  // Handle Play/Pause
  useEffect(() => {
    if (isPlaying) {
      step();
    } else {
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
      }
    }
    return () => {
      if (timeoutRef.current) clearTimeout(timeoutRef.current);
    };
  }, [isPlaying, step]);

  const handleReset = () => {
    setIsPlaying(false);
    if (timeoutRef.current) clearTimeout(timeoutRef.current);
    generateData(arraySize);
    generatorRef.current = null;
    setActiveLine(undefined);
  };

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col text-slate-800 font-sans selection:bg-indigo-100">
      
      {/* Header */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-30 shadow-sm">
        <div className="max-w-[1400px] mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-gradient-to-br from-indigo-500 to-violet-600 rounded-lg flex items-center justify-center text-white font-bold text-lg shadow-md">
              Z
            </div>
            <h1 className="text-xl font-bold tracking-tight text-slate-800">Zengorithms</h1>
          </div>
          <a 
            href="https://github.com/Moeez404/zengorithms" 
            target="_blank" 
            rel="noopener noreferrer"
            className="text-slate-400 hover:text-slate-600 transition-colors p-2 rounded-full hover:bg-slate-50"
            aria-label="View Source on GitHub"
          >
            <Github size={20} />
          </a>
        </div>
      </header>

      <main className="flex-1 max-w-[1400px] mx-auto w-full px-4 py-6">
        
        {/* Main Grid Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 h-full">
          
          {/* Left Column: Visualizer & Controls (8 cols) */}
          <div className="lg:col-span-8 flex flex-col gap-6">
             {/* Visualizer Area */}
            <section className="flex-1 min-h-[400px] lg:min-h-[500px]">
               {selectedAlgo.type === 'sorting' && <Visualizer array={array} />}
               {selectedAlgo.type === 'tree' && <TreeVisualizer root={treeRoot} />}
               {selectedAlgo.type === 'graph' && <GraphVisualizer nodes={graphState.nodes} edges={graphState.edges} />}
            </section>

            {/* Controls */}
            <Controls 
              selectedAlgoId={selectedAlgo.id}
              setSelectedAlgoId={(id) => {
                 const algo = ALGORITHMS.find(a => a.id === id);
                 if (algo) setSelectedAlgo(algo);
              }}
              arraySize={arraySize}
              setArraySize={setArraySize}
              speed={speed}
              setSpeed={setSpeed}
              isPlaying={isPlaying}
              onPlay={() => setIsPlaying(true)}
              onPause={() => setIsPlaying(false)}
              onReset={handleReset}
              isSorted={isSorted}
            />
          </div>

          {/* Right Column: Info, Code, Status (4 cols) */}
          <div className="lg:col-span-4 flex flex-col gap-4">
             {/* Algorithm Description */}
             <section className="bg-white rounded-2xl p-5 border border-slate-100 shadow-sm">
                <div className="flex items-center gap-2 mb-2">
                    <div className="p-1.5 bg-indigo-100 rounded-lg text-indigo-600">
                        <Info size={16} />
                    </div>
                    <h2 className="font-bold text-slate-800">{selectedAlgo.name}</h2>
                </div>
                <p className="text-slate-600 text-sm leading-relaxed">
                    {selectedAlgo.description}
                </p>
             </section>

             {/* Code Viewer */}
             <section className="flex-1 max-h-[400px]">
                 <CodeViewer 
                    code={selectedAlgo.code} 
                    activeLine={activeLine}
                 />
             </section>

             {/* Terminal Status */}
             <section className="bg-slate-900 rounded-2xl p-4 border border-slate-800 shadow-inner">
                <div className="flex items-center gap-2 text-slate-400 mb-2 text-xs font-mono uppercase tracking-wider">
                    <Terminal size={12} />
                    <span>Execution Log</span>
                </div>
                <div className="font-mono text-xs sm:text-sm text-emerald-400 leading-snug break-words">
                    {`> ${currentStepDescription}`}
                    <span className="inline-block w-1.5 h-3 bg-emerald-400 ml-1 animate-pulse align-middle"></span>
                </div>
            </section>
             
             {/* PQ Visualization (Optional for Graph) */}
             {selectedAlgo.type === 'graph' && array.length > 0 && (
                <section className="bg-white rounded-2xl p-4 border border-slate-100 shadow-sm">
                    <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Priority Queue</h3>
                    <div className="flex gap-2 h-16 items-end">
                        {array.map(bar => (
                             <div key={bar.id} className="flex flex-col items-center flex-1">
                                <div className="w-full bg-indigo-400 rounded-t-sm" style={{height: `${bar.value}%`}}></div>
                                <span className="text-[10px] text-slate-600 font-mono mt-1 whitespace-nowrap overflow-hidden text-ellipsis max-w-full">{bar.label ? bar.label.split(':')[0] : ''}</span>
                             </div>
                        ))}
                    </div>
                </section>
             )}
          </div>

        </div>
      </main>

      <AITutor algorithmName={selectedAlgo.name} />
    </div>
  );
};

export default App;